<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CNPIKI9" failures="1" tests="2" name="Sample tests" time="0.123" errors="0" timestamp="2023-03-25T23:57:55 IST">
  <testcase classname="Tests" name="test1" time="0.009"/>
  <testcase classname="Tests" name="test2" time="0.031">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Tests.test2(Tests.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Sample tests -->
